"""Add auth

Revision ID: 2d7591fb702c
Revises: 7e4f5a6b7c8d
Create Date: 2026-07-30 20:32:00.255569

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2d7591fb702c'
down_revision: str | Sequence[str] | None = '7e4f5a6b7c8d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True))
    
    # Never set a real default password for existing users. Assign a random
    # non-argon2 string so any pre-existing accounts cannot be logged into.
    op.execute("UPDATE users SET hashed_password = md5(random()::text || clock_timestamp()::text) WHERE hashed_password IS NOT NULL")
    op.execute("UPDATE users SET is_active = true")

    op.alter_column('users', 'hashed_password', existing_type=sa.String(length=255), nullable=False)
    op.alter_column('users', 'is_active', existing_type=sa.Boolean(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
