"""Add auth

Revision ID: 2d7591fb702c
Revises: 7e4f5a6b7c8d
Create Date: 2026-07-30 20:32:00.255569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7591fb702c'
down_revision: Union[str, Sequence[str], None] = '7e4f5a6b7c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True))
    
    # Set default password ("password123") for existing mock users
    op.execute("UPDATE users SET hashed_password = '$2b$12$N.5y3.6e7R1tX5vKqJ.R0uF4lP4sMv0kR4lP4sMv0kR4lP4sMv0k'")
    op.execute("UPDATE users SET is_active = true")

    op.alter_column('users', 'hashed_password', existing_type=sa.String(length=255), nullable=False)
    op.alter_column('users', 'is_active', existing_type=sa.Boolean(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
