"""add_dimension_values_to_daily_rollups

Revision ID: cd678bef8820
Revises: c3cbb107211d
Create Date: 2026-07-21 10:59:45.023712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd678bef8820'
down_revision: Union[str, Sequence[str], None] = 'c3cbb107211d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_rollups', sa.Column('dimension_values', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.create_index('uq_daily_rollups_metric_date_dims', 'daily_rollups', ['metric_id', 'date', 'dimension_values'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_daily_rollups_metric_date_dims', table_name='daily_rollups')
    op.drop_column('daily_rollups', 'dimension_values')
    # ### end Alembic commands ###
