"""add_unique_to_anomalies

Revision ID: db622994a7d7
Revises: cd678bef8820
Create Date: 2026-07-21 11:11:53.282480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db622994a7d7'
down_revision: Union[str, Sequence[str], None] = 'cd678bef8820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Delete duplicate anomalies first
    op.execute(
        "DELETE FROM anomalies a USING anomalies b "
        "WHERE a.id < b.id AND a.metric_id = b.metric_id AND a.date = b.date;"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_anomalies_metric_date', 'anomalies', ['metric_id', 'date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_anomalies_metric_date', table_name='anomalies')
    # ### end Alembic commands ###
